"""small changes to alarms table

Revision ID: 0a3736b90c9c
Revises: 507b40cae12e
Create Date: 2022-10-31 20:04:15.421580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3736b90c9c'
down_revision = '507b40cae12e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alarms_ibfk_1', 'alarms', type_='foreignkey')
    op.create_foreign_key(None, 'alarms', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alarms', type_='foreignkey')
    op.create_foreign_key('alarms_ibfk_1', 'alarms', 'properties', ['property_id'], ['id'])
    # ### end Alembic commands ###
