"""added property_id column to intrusion

Revision ID: 6861f6d5e59e
Revises: 9d05624c7d46
Create Date: 2022-11-11 21:17:01.224127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6861f6d5e59e'
down_revision = '9d05624c7d46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intrusions', sa.Column('property_id', sa.Integer(), nullable=True))
    op.add_column('intrusions', sa.Column('datetime', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intrusions', 'datetime')
    op.drop_column('intrusions', 'property_id')
    # ### end Alembic commands ###
