"""added camera table and additional fields for cameras and alarms

Revision ID: 948d7dcd460b
Revises: 6861f6d5e59e
Create Date: 2022-11-13 17:35:09.032996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948d7dcd460b'
down_revision = '6861f6d5e59e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('is_streaming', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alarms', sa.Column('is_alive', sa.Boolean(), nullable=False))
    op.add_column('alarms', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarms', 'is_active')
    op.drop_column('alarms', 'is_alive')
    op.drop_table('cameras')
    # ### end Alembic commands ###
