"""delete user table

Revision ID: a2cfdea2881f
Revises: 948d7dcd460b
Create Date: 2022-12-13 18:25:35.756271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2cfdea2881f'
down_revision = '948d7dcd460b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('properties_ibfk_1', 'properties', type_='foreignkey')
    op.drop_constraint('intrusions_ibfk_1', 'intrusions', type_='foreignkey')
    op.alter_column('intrusions', 'property_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index(op.f('ix_intrusions_user_id'), 'intrusions', ['user_id'], unique=False)
    op.alter_column('properties', 'owner_id',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_foreign_key('properties_ibfk_1', 'properties', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('intrusions_ibfk_1', 'intrusions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('properties', 'owner_id',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('intrusions', 'property_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index(op.f('ix_intrusions_user_id'), table_name='intrusions')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    # ### end Alembic commands ###
